<script setup lang="ts">
import { ref, computed, onMounted, nextTick, watch } from 'vue';
import { useHead } from '@unhead/vue';
import axios from 'axios';
import { useRouter } from 'vue-router';
import QRCodeStyling from 'qr-code-styling';
import SideNav from '../components/SideNav.vue';
import TopNav from '../components/TopNav.vue';
import { useI18n } from '../i18n';
import { useToast } from '../composables/useToast';
import { getAuthHeaders } from '../composables/useAuth';
import { API_URL } from '@/config/api';

const router = useRouter();
const { t } = useI18n();
const toast = useToast();
useHead({ title: () => `${t('profile.title')} — QReturn` });

const platforms = ['wa', 'ig', 'fb', 'tg'] as const;
const platformLabels: Record<string, string> = { wa: 'WhatsApp', ig: 'Instagram', fb: 'Facebook', tg: 'Telegram' };
const platformUrls: Record<string, string> = { wa: 'https://wa.me/', ig: 'https://instagram.com/', fb: 'https://facebook.com/', tg: 'https://t.me/' };

const profile = ref<any>({});
const username = ref('');
const bio = ref('');
const contacts = ref<{ platform: string; value: string }[]>([]);
const isSaving = ref(false);
const isLoading = ref(true);
const usernameAutoGenerated = ref(false);
const usernameLocked = ref(false);
const showConfirmation = ref(false);
let originalAutoSlug = '';

const qrContainer = ref<HTMLElement | null>(null);
const qrTagline = ref('this item is owned!');
const taglineBold = ref(true);
let qrCode: QRCodeStyling | null = null;

const profileUrl = computed(() => {
  if (!username.value) return window.location.origin + '/profile/me';
  return `${window.location.origin}/profile/${username.value}`;
});

const pendingPreviewUrl = computed(() => {
  const slug = (usernameAutoGenerated.value && username.value === originalAutoSlug)
    ? originalAutoSlug
    : (username.value || 'username');
  return `${window.location.origin}/profile/${slug}`;
});

const usedPlatforms = computed(() => contacts.value.map(c => c.platform));
const availablePlatforms = computed(() => platforms.filter(p => !usedPlatforms.value.includes(p)));

const addContact = () => {
  if (contacts.value.length >= 3) return;
  const avail = availablePlatforms.value;
  if (avail.length === 0) return;
  contacts.value.push({ platform: avail[0] as typeof platforms[number], value: '' });
};

const removeContact = (index: number) => {
  contacts.value.splice(index, 1);
};

const getPlatformPlaceholder = (platform: string) => {
  if (platform === 'wa') return t('profile.wa_placeholder');
  return t('profile.social_placeholder');
};

const slugFromName = (name: string) => {
  return name.trim().replace(/\s+/g, '').replace(/[^a-zA-Z0-9]/g, '') || 'user';
};

const loadProfile = async () => {
  try {
    const res = await axios.get(`${API_URL}/api/profile/me`, { headers: await getAuthHeaders() });
    const p = res.data.profile;
    profile.value = p;
    if (p.username) {
      username.value = p.username;
      usernameAutoGenerated.value = false;
      usernameLocked.value = true;
    } else {
      originalAutoSlug = slugFromName(p.nama || '');
      username.value = originalAutoSlug;
      usernameAutoGenerated.value = true;
      usernameLocked.value = false;
    }
    bio.value = p.bio || '';
    contacts.value = [];
    for (const plat of platforms) {
      if (p[plat]) {
        contacts.value.push({ platform: plat, value: p[plat] });
      }
    }
  } catch (e: any) {
    toast.show(e.response?.data?.message || 'Failed to load profile', 'error');
  } finally {
    isLoading.value = false;
  }
};

const buildSaveBody = () => {
  const body: any = { bio: bio.value || null };
  if (usernameLocked.value) {
    body.username = profile.value.username;
  } else if (usernameAutoGenerated.value && username.value === originalAutoSlug) {
    // skip — backend auto-generates with dedup
  } else {
    body.username = username.value || null;
  }
  for (const c of contacts.value) {
    body[c.platform] = c.value || null;
  }
  return body;
};

const doSave = async () => {
  isSaving.value = true;
  try {
    const body = buildSaveBody();
    await axios.put(`${API_URL}/api/profile/me`, body, { headers: await getAuthHeaders() });
    toast.show(t('profile.saved'), 'success');
    showConfirmation.value = false;
    await loadProfile();
    regenerateQR();
  } catch (e: any) {
    const msg = e.response?.data?.message || 'Failed to save profile';
    if (msg.toLowerCase().includes('username already taken')) {
      toast.show(t('profile.username_taken'), 'error');
    } else {
      toast.show(msg, 'error');
    }
  } finally {
    isSaving.value = false;
  }
};

const saveProfile = async () => {
  if (contacts.value.length > 3) {
    toast.show(t('profile.max_3_contacts'), 'error');
    return;
  }
  if (!usernameLocked.value) {
    showConfirmation.value = true;
    return;
  }
  await doSave();
};

const loadLogo = async (): Promise<string> => {
  try {
    const res = await fetch('/logo.png');
    const blob = await res.blob();
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => resolve(reader.result as string);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
  } catch {
    return '';
  }
};

const regenerateQR = async () => {
  if (!qrContainer.value || !username.value) return;
  if (qrCode) {
    qrContainer.value.innerHTML = '';
    qrCode = null;
  }

  const logoDataUrl = await loadLogo();

  qrCode = new QRCodeStyling({
    width: 180,
    height: 180,
    data: profileUrl.value,
    qrOptions: { errorCorrectionLevel: 'H' },
    dotsOptions: { color: '#387b41', type: 'rounded' },
    cornersSquareOptions: { color: '#387b41', type: 'extra-rounded' },
    cornersDotOptions: { color: '#387b41', type: 'dot' },
    backgroundOptions: { color: '#ffffff' },
    image: logoDataUrl,
    imageOptions: { hideBackgroundDots: true, imageSize: 0.4, margin: 8 },
  });

  qrCode.append(qrContainer.value);
  nextTick(() => renderCompositePreview());
};

const getQrCanvas = (): HTMLCanvasElement | null => {
  if (!qrContainer.value) return null;
  return qrContainer.value.querySelector('canvas');
};

const compositeWithTagline = (canvas: HTMLCanvasElement): HTMLCanvasElement => {
  let tagline = qrTagline.value.trim().slice(0, 30) || 'this item is owned!';
  const padBottom = 16;
  const textHeight = 48;
  const fontSize = 22;

  const combined = document.createElement('canvas');
  combined.width = Math.max(canvas.width, 280);
  combined.height = canvas.height + textHeight + padBottom;

  const ctx = combined.getContext('2d')!;
  ctx.fillStyle = '#ffffff';
  ctx.fillRect(0, 0, combined.width, combined.height);

  const offsetX = Math.floor((combined.width - canvas.width) / 2);
  ctx.drawImage(canvas, offsetX, 0);

  ctx.fillStyle = '#387b41';
  const weight = taglineBold.value ? '700' : '400';
  ctx.font = `${weight} ${fontSize}px "Space Grotesk", sans-serif`;
  ctx.textAlign = 'center';
  ctx.textBaseline = 'top';

  const textX = combined.width / 2;
  const textY = canvas.height + padBottom;

  ctx.fillText(`${tagline}`, textX, textY);

  return combined;
};

const compositePreviewRef = ref<HTMLElement | null>(null);

const renderCompositePreview = () => {
  const canvas = getQrCanvas();
  if (!canvas || !compositePreviewRef.value) return;
  const combined = compositeWithTagline(canvas);
  const preview = compositePreviewRef.value;
  preview.innerHTML = '';
  const img = document.createElement('img');
  img.src = combined.toDataURL('image/png');
  img.className = 'max-w-full h-auto rounded-xl border border-[#e0e4df] dark:border-[#374151]';
  preview.appendChild(img);
};

watch([qrTagline, taglineBold], () => {
  nextTick(() => renderCompositePreview());
});

const downloadQR = () => {
  const canvas = getQrCanvas();
  if (!canvas) return;
  const combined = compositeWithTagline(canvas);
  const link = document.createElement('a');
  link.download = 'qreturn-profile.png';
  link.href = combined.toDataURL('image/png');
  link.click();
};

const printQR = () => {
  const canvas = getQrCanvas();
  if (!canvas) return;
  const combined = compositeWithTagline(canvas);
  const dataUrl = combined.toDataURL('image/png');
  const win = window.open('', '_blank');
  if (!win) return;
  win.document.write(`
    <html><head><title>QReturn Profile QR</title>
    <style>body{display:flex;justify-content:center;align-items:center;height:100vh;margin:0;background:#fff}img{max-width:90vw}</style>
    </head><body>
    <img src="${dataUrl}" />
    </body></html>
  `);
  win.document.close();
  win.print();
};

onMounted(async () => {
  await loadProfile();
  await nextTick();
  setTimeout(() => regenerateQR(), 300);
});

watch(username, () => {
  regenerateQR();
});
</script>

<template>
  <div class="min-h-screen bg-[#f8faf7] dark:bg-[#121212] flex font-sans">
    <SideNav />
    <TopNav />

    <main class="md:ml-64 pt-24 px-4 sm:px-6 md:px-8 pb-12 flex-1 min-w-0">
      <button @click="router.back()" class="flex items-center gap-2 text-[#40493d] dark:text-[#9ca3af] hover:text-[#387b41] mb-8 transition-colors font-bold text-sm group">
        <span class="material-symbols-outlined group-hover:-translate-x-1 transition-transform">arrow_back</span>
        {{ t('detail.back') }}
      </button>

      <div v-if="isLoading" class="flex justify-center py-20">
        <div class="w-10 h-10 border-4 border-[#387b41]/20 border-t-[#387b41] rounded-full animate-spin"></div>
      </div>

      <div v-else class="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <!-- Left: Profile Form -->
        <div class="bg-white dark:bg-[#1e1e1e] rounded-[2.5rem] p-6 sm:p-8 border border-[#e0e4df] dark:border-[#374151] shadow-sm space-y-6">
          <h2 class="text-2xl font-bold text-[#1c1b1b] dark:text-[#f3f4f6]">{{ t('profile.edit_title') }}</h2>

          <div class="space-y-2">
            <label class="text-xs font-bold text-[#40493d] dark:text-[#9ca3af] uppercase tracking-wider">{{ t('profile.username') }}</label>
            <div v-if="usernameLocked" class="p-3 bg-[#ffecb3] rounded-2xl flex items-start gap-2 mb-2">
              <span class="material-symbols-outlined text-sm text-[#f57f17] shrink-0">lock</span>
              <p class="text-[11px] text-[#5f4339] font-medium leading-relaxed">Username cannot be changed after it has been set.</p>
            </div>
            <input v-model="username" type="text" placeholder="johndoe" maxlength="50" :disabled="usernameLocked"
              :class="['w-full bg-[#f3f5f2] dark:bg-[#2a2a2a] dark:text-white dark:placeholder-gray-500 border-2 border-transparent rounded-xl px-5 py-4 outline-none transition-all text-sm font-medium', 
              usernameLocked ? 'opacity-60 cursor-not-allowed' : 'focus:border-[#387b41] focus:bg-white dark:focus:bg-[#1e1e1e]']" />
          </div>

          <div class="space-y-2">
            <label class="text-xs font-bold text-[#40493d] dark:text-[#9ca3af] uppercase tracking-wider">{{ t('profile.bio') }}</label>
            <textarea v-model="bio" rows="3" maxlength="200" placeholder="Tell others about yourself..."
              class="w-full bg-[#f3f5f2] dark:bg-[#2a2a2a] dark:text-white dark:placeholder-gray-500 border-2 border-transparent rounded-xl px-5 py-4 focus:border-[#387b41] focus:bg-white dark:focus:bg-[#1e1e1e] outline-none transition-all text-sm font-medium resize-none"></textarea>
          </div>

          <div class="space-y-3">
            <div class="flex items-center justify-between">
              <label class="text-xs font-bold text-[#40493d] dark:text-[#9ca3af] uppercase tracking-wider">{{ t('profile.contact') }} ({{ contacts.length }}/3)</label>
              <button v-if="contacts.length < 3" @click="addContact" type="button"
                class="text-xs font-bold text-[#387b41] hover:underline flex items-center gap-1">
                <span class="material-symbols-outlined text-sm">add</span>
                {{ t('profile.add_contact') }}
              </button>
            </div>

            <div v-for="(contact, i) in contacts" :key="i" class="flex gap-2 items-start">
              <select v-model="contact.platform"
                class="bg-[#f3f5f2] dark:bg-[#2a2a2a] dark:text-white border-2 border-transparent rounded-xl px-3 py-4 focus:border-[#387b41] outline-none transition-all text-xs font-medium appearance-none shrink-0 w-[130px]">
                <option v-for="p in [contact.platform, ...availablePlatforms.filter(x => x !== contact.platform)]" :key="p" :value="p">{{ platformLabels[p] }}</option>
              </select>
              <input v-model="contact.value" :placeholder="getPlatformPlaceholder(contact.platform)" maxlength="50"
                class="flex-1 bg-[#f3f5f2] dark:bg-[#2a2a2a] dark:text-white dark:placeholder-gray-500 border-2 border-transparent rounded-xl px-4 py-4 focus:border-[#387b41] focus:bg-white dark:focus:bg-[#1e1e1e] outline-none transition-all text-sm font-medium" />
              <button @click="removeContact(i)" type="button" class="p-4 text-[#ba1a1a] hover:bg-[#fef2f2] dark:hover:bg-red-950/20 rounded-xl transition-colors">
                <span class="material-symbols-outlined text-lg">close</span>
              </button>
            </div>

            <p v-if="!contacts.length" class="text-xs text-[#40493d] dark:text-[#9ca3af]/50 italic px-1">{{ t('profile.add_contact') }} ↑</p>
          </div>

          <button @click="saveProfile" :disabled="isSaving"
            class="w-full py-4 bg-[#387b41] text-white rounded-2xl font-bold text-base hover:bg-[#2d6334] transition-all active:scale-95 disabled:opacity-50 flex items-center justify-center gap-2">
            <span v-if="isSaving" class="material-symbols-outlined animate-spin">sync</span>
            {{ isSaving ? '' : t('profile.save') }}
          </button>
        </div>

        <!-- Right: QR Code Preview -->
        <div class="bg-white dark:bg-[#1e1e1e] rounded-[2.5rem] p-6 sm:p-8 border border-[#e0e4df] dark:border-[#374151] shadow-sm space-y-6">
          <h2 class="text-2xl font-bold text-[#1c1b1b] dark:text-[#f3f4f6]">{{ t('profile.qr_title') }}</h2>
          <p class="text-sm text-[#40493d] dark:text-[#9ca3af]">{{ t('profile.qr_desc') }}</p>

          <div v-if="!username" class="p-6 bg-[#ffecb3] rounded-2xl flex items-start gap-3">
            <span class="material-symbols-outlined text-[#f57f17] text-sm shrink-0">info</span>
            <p class="text-xs text-[#5f4339] font-medium">Set a username first to generate your profile QR code.</p>
          </div>

          <div v-if="username" ref="qrContainer" class="flex justify-center p-4 bg-white rounded-2xl border border-[#e0e4df]"></div>

          <!-- Tagline editor -->
          <div v-if="username" class="space-y-2">
            <label class="text-xs font-bold text-[#40493d] dark:text-[#9ca3af] uppercase tracking-wider">Tagline ({{ qrTagline.length }}/30)</label>
            <div class="flex items-center gap-2 p-3 bg-[#f3f5f2] dark:bg-[#2a2a2a] rounded-2xl border border-[#e0e4df] dark:border-[#374151]">
              <span class="material-symbols-outlined text-[#387b41] text-lg">loyalty</span>
              <input v-model="qrTagline" type="text" maxlength="30" placeholder="this item is owned!"
                class="flex-1 bg-transparent border-none outline-none text-sm font-medium text-[#1c1b1b] dark:text-[#f3f4f6] placeholder:text-[#40493d]/40" />
              <button @click="taglineBold = !taglineBold" type="button"
                :class="['px-2 py-1 rounded-lg text-xs font-bold transition-all', taglineBold ? 'bg-[#387b41] text-white' : 'bg-[#e0e4df] dark:bg-[#374151] text-[#40493d] dark:text-[#9ca3af]']">
                <span style="font-family:'Space Grotesk',sans-serif" class="tracking-tight font-bold">B</span>
              </button>
            </div>
          </div>

          <!-- Live composite preview (QR + tagline, exactly what downloads) -->
          <div v-if="username" ref="compositePreviewRef" class="flex justify-center"></div>

          <div v-if="username" class="flex gap-3">
            <button @click="downloadQR" class="flex-1 py-3 bg-[#387b41] text-white rounded-xl font-bold text-sm hover:bg-[#2d6334] transition-all active:scale-95 flex items-center justify-center gap-2">
              <span class="material-symbols-outlined text-lg">download</span>
              {{ t('profile.download_qr') }}
            </button>
            <button @click="printQR" class="flex-1 py-3 bg-[#f3f5f2] dark:bg-[#2a2a2a] text-[#40493d] dark:text-[#9ca3af] rounded-xl font-bold text-sm hover:bg-[#e0e4df] dark:hover:bg-[#374151] transition-all flex items-center justify-center gap-2">
              <span class="material-symbols-outlined text-lg">print</span>
              {{ t('profile.print_qr') }}
            </button>
          </div>

          <div v-if="username" class="p-4 bg-[#f3f5f2] dark:bg-[#2a2a2a] rounded-2xl">
            <p class="text-[10px] font-bold text-[#40493d] dark:text-[#9ca3af] uppercase tracking-wider mb-1">{{ t('profile.public_title') }}</p>
            <p class="text-xs text-[#387b41] font-mono break-all">{{ profileUrl }}</p>
          </div>
        </div>
      </div>
    </main>

    <!-- Confirmation Modal -->
    <Teleport to="body">
      <div v-if="showConfirmation" class="fixed inset-0 z-50 flex items-center justify-center p-4" @click.self="showConfirmation = false">
        <div class="absolute inset-0 bg-black/50 backdrop-blur-sm"></div>
        <div class="relative bg-white dark:bg-[#1e1e1e] rounded-[2rem] p-6 sm:p-8 w-full max-w-md border border-[#e0e4df] dark:border-[#374151] shadow-2xl animate-fade-in">
          <div class="flex items-center gap-3 mb-6">
            <div class="w-10 h-10 bg-[#ffecb3] rounded-xl flex items-center justify-center">
              <span class="material-symbols-outlined text-[#f57f17]">link</span>
            </div>
            <div>
              <h3 class="text-lg font-bold text-[#1c1b1b] dark:text-[#f3f4f6]">Confirm Your Profile URL</h3>
              <p class="text-xs text-[#40493d] dark:text-[#9ca3af]">This cannot be changed later.</p>
            </div>
          </div>

          <div class="p-4 bg-[#f3f5f2] dark:bg-[#2a2a2a] rounded-2xl mb-6">
            <p class="text-[10px] font-bold text-[#40493d] dark:text-[#9ca3af] uppercase tracking-wider mb-2">Your public profile will be at:</p>
            <p class="text-sm text-[#387b41] font-mono font-bold break-all leading-relaxed">{{ pendingPreviewUrl }}</p>
          </div>

          <div class="p-3 bg-[#ffecb3] rounded-2xl flex items-start gap-2 mb-6">
            <span class="material-symbols-outlined text-sm text-[#f57f17] shrink-0">warning</span>
            <p class="text-[11px] text-[#5f4339] font-medium leading-relaxed">Once saved, the username (and your profile URL) cannot be changed. Make sure it looks right before confirming.</p>
          </div>

          <div class="flex gap-3">
            <button @click="showConfirmation = false"
              class="flex-1 py-3 bg-[#f3f5f2] dark:bg-[#2a2a2a] text-[#40493d] dark:text-[#9ca3af] rounded-xl font-bold text-sm hover:bg-[#e0e4df] dark:hover:bg-[#374151] transition-all">
              Cancel
            </button>
            <button @click="doSave" :disabled="isSaving"
              class="flex-1 py-3 bg-[#387b41] text-white rounded-xl font-bold text-sm hover:bg-[#2d6334] transition-all disabled:opacity-50 flex items-center justify-center gap-2">
              <span v-if="isSaving" class="material-symbols-outlined text-sm animate-spin">sync</span>
              {{ isSaving ? '' : 'Yes, Save' }}
            </button>
          </div>
        </div>
      </div>
    </Teleport>
  </div>
</template>
