-- Add profile fields for Profile + QR feature
ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS username VARCHAR(50) UNIQUE,
  ADD COLUMN IF NOT EXISTS bio VARCHAR(200),
  ADD COLUMN IF NOT EXISTS wa VARCHAR(20),
  ADD COLUMN IF NOT EXISTS ig VARCHAR(50),
  ADD COLUMN IF NOT EXISTS fb VARCHAR(50),
  ADD COLUMN IF NOT EXISTS tg VARCHAR(50);

CREATE INDEX IF NOT EXISTS idx_profiles_username ON profiles(username);
